os: linux
language: go
go:
- 1.15.1  # Bazel still uses its own version
env:
  global:
  - BAZEL_VERSION=3.5.0
  - BAZEL_SHA256=8b92c871dc85afc74f4e1c55992b8edd2984b52df809009afaa290fad7587973
before_install:
- |
  wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
  echo "${BAZEL_SHA256}  install.sh" | sha256sum -c
  chmod +x install.sh
install:
- |
  ./install.sh --user
  rm -f install.sh
script:
- travis_wait bazel build --config=ci //...
- bazel test --config=ci //...
- go build
- go test
